[package]
name = "sha256-inline-guest-128"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", git = "https://github.com/a16z/jolt.git", rev = "b10e80ac" }
jolt-inlines-sha2 = { git = "https://github.com/a16z/jolt.git", rev = "b10e80ac" }

[package.metadata.cargo-machete]
ignored = ["jolt-inlines-sha2"]
